### PR TITLE
Update contexts.md

### PR DESCRIPTION
**Pull request by weisisheng**
fixed some misc. typos

### CODE REVIEW

**Review by apoliakov — APPROVED** [review]
Thanks Vince!

**Comment by qianl15** [comment]
Actually, they are not typos -- `TransactionContext<T>` indicates it accepts a generic type parameter `T`, which is explained in the following paragraph.

**Comment by apoliakov** [comment]
@qianl15 looks like the <T> was removed erroneously but Vince also fixed a typo in "transactioncontextt"

**Comment by apoliakov** [comment]
Ah I think I see the intent. The misspelling "transactioncontextt" is purposeful. Sorry about that!

**Pull request closed without merging**
